### ISSUE TITLE
get RocksDB perf counters into SHOW GLOBAL STATUS

### ISSUE THREAD

**Issue by mdcallag** [MariaDB/webscalesql-5.6#19]
It will help a lot to have RocksDB perf counters in SHOW GLOBAL STATUS output for RocksDB + MySQL. For info on SHOW STATUS see http://dev.mysql.com/doc/refman/5.0/en/show-status.html.

For InnoDB, see innodb_status_variables in https://github.com/MariaDB/webscalesql-5.6/blob/webscalesql-5.6.19/storage/innobase/handler/ha_innodb.cc

For RocksDB, see rocksdb_status_variables in https://github.com/MariaDB/webscalesql-5.6/blob/webscalesql-5.6.19/storage/rocksdb/ha_rocksdb.cc

For RocksDB entry points, see include/rocksdb/options.h and in db/db_bench.cc the function PrintStats that calls db->GetProperty("rocksdb.stats",...)

bin/mysql -A -e 'show global status' | grep -i rocksdb

rocksdb_bytes_written   2372229291762
rocksdb_bytes_read      7763473524122
rocksdb_number_keys_written     25970022279
rocksdb_number_keys_read        160304813639
rocksdb_number_keys_updated     0

**Comment by jonahcohen** [comment]
https://github.com/MariaDB/webscalesql-5.6/commit/daef738c9b45de06c2aa9f13ca9fea4dabed04ce
