### ISSUE TITLE
support my.cnf options to configure RocksDB

### ISSUE THREAD

**Issue by mdcallag** [MariaDB/webscalesql-5.6#20]

**Comment by jonahcohen** [comment]
ColumnFamilyOptions support:
https://github.com/jonahcohen/webscalesql-5.6/commit/16a29f36b8175f75e9dca762f2831da41bb85d9a
https://github.com/jonahcohen/webscalesql-5.6/commit/b0ecdc6eade3afabd6b21e9c6278fa9e5165f665

DBOptions support:
https://github.com/jonahcohen/webscalesql-5.6/commit/ebfd8f0ecd283032f6c684fc046a8d982650cf12

**Comment by mdcallag** [comment]
From DBOptions in options.h, missing support for:
info_log_level
stats_dump_period_sec

**Comment by jonahcohen** [comment]
Added stats_dump_period_sec:
https://github.com/MariaDB/webscalesql-5.6/commit/fac1d305a0810faf7a5d5ba8dde80bd1419b3f9d

**Comment by jonahcohen** [comment]
Added info_log_level:
https://github.com/MariaDB/webscalesql-5.6/commit/e1e7b859176978d5ff8ea485a4decdfc7d687a93
